<?php
return [
      'tradeFee'=>0.002,

      'withdraw'=>[
          'uah'=>[
              'visa/mastercard'=>[
                  'fee'=>0.08,
                  'additionFee'=>30,
                  'minAmountPerOperation'=>100,
                  'maxAmountPerOperation'=>10000,
                  'maxAmountPerDay'=>100000,
                  'maxAmountPerMonth'=>300000,
              ],
              'advCash'=>[
                  'fee'=>0.06,
                  'maxAmountPerOperation'=>15000,
              ]
          ],
          'btc'=>[
              'fee'=>0.0005,
              'minAmountPerOperation'=>0.01,
              'maxAmountPerOperation'=>350,
          ],
          'eth'=>[
              'fee'=>0.01,
              'minAmountPerOperation'=>0.1,
              'maxAmountPerOperation'=>500,
          ],
          'zec'=>[
              'fee'=>0.001,
              'minAmountPerOperation'=>0.01,
              'maxAmountPerOperation'=>500
          ],
          'nmc'=>[
              'fee'=>0.1,
              'minAmountPerOperation'=>0.2,
              'maxAmountPerOperation'=>50000
          ],
          'btg'=>[
              'fee'=>0.001,
              'minAmountPerOperation'=>0.01,
              'maxAmountPerOperation'=>1000000
          ],
          'hbz'=>[
              'fee'=>65,
              'minAmountPerOperation'=>100,
              'maxAmountPerOperation'=>1000000
          ],
          'btcz'=>[
              'fee'=>15,
              'minAmountPerOperation'=>2500,
              'maxAmountPerOperation'=>1000000
          ],
          'dxt'=>[
              'fee'=>20,
              'minAmountPerOperation'=>100,
              'maxAmountPerOperation'=>1000000
          ],
          'xlm'=>[
              'fee'=>0.01,
              'minAmountPerOperation'=>21,
              'maxAmountPerOperation'=>1000000
          ],
      ],
      'deposit'=>[
          'uah'=>[
              'fee'=>0.026,
              'maxAmountPerOperation'=>15000,
              'maxNumberOperationsPerDay'=>5,
          ],
      ]
];